name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Create requirements_dev.txt if not exists
        run: |
          if [ ! -f requirements_dev.txt ]; then
            echo "homeassistant==2023.12.1" > requirements_dev.txt
            echo "pre-commit==3.5.0" >> requirements_dev.txt
            echo "pylint==3.0.2" >> requirements_dev.txt
            echo "black==23.11.0" >> requirements_dev.txt
            echo "flake8==6.1.0" >> requirements_dev.txt
            echo "isort==5.12.0" >> requirements_dev.txt
            echo "pymodbus>=3.0.0" >> requirements_dev.txt
            pip install -r requirements_dev.txt
          fi

      - name: Validate with HACS
        uses: hacs/action@main
        with:
          category: integration

      - name: Validate with hassfest
        uses: home-assistant/actions/hassfest@master
        
      - name: Lint with flake8
        run: |
          flake8 custom_components/ --count --select=E9,F63,F7,F82 --show-source --statistics 